on: push
name: CI
jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            +(src)/**/*.cpp
      - name: Check for differences
        if: env.GIT_DIFF
        run: |
          echo "Diff ${{ env.GIT_DIFF }}"
          echo "Diff filtered ${{ env.GIT_DIFF_FILTERED }}"
