on: push
name: CI
jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest
    steps:
      # Prepare project repository.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # We need to fetch 2 commits to get the diff.
      
      - name: Get differences
        run: |
          DIFFS="$(git diff --name-only HEAD HEAD~1)"
          CHANGES="$(echo $DIFFS | grep 'src.*cpp')"
          echo "FLAG=$?" >> $GITHUB_ENV

      - name: Differences on current module
        if: env.FLAG
        run: echo "$FLAG"
