on: push
name: CI
jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - dependencies: 'src.*one.*cpp|src.*two.*cpp'
            path: src/one
          - dependencies: 'src.*two.*cpp'
            path: src/two
    steps:
      # Prepare project repository.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # We need to fetch 2 commits to get the diff.
      
      - name: Check for compilation requirement
        run: |
          
          DIFFS=$(git diff --name-only HEAD HEAD~1)
          if echo $DIFFS | grep -E '${{ matrix.project.dependencies }}'; then
            echo "COMPILATION_FLAG=true" >> $GITHUB_ENV
            echo "COMPILATION_FLAG2=\"true\"" >> $GITHUB_ENV
            echo "COMPILATION_FLAG2=\"false\"" >> $GITHUB_ENV            
          else
            echo "COMPILATION_FLAG=false" >> $GITHUB_ENV
            echo "COMPILATION_FLAG3=true" >> $GITHUB_ENV            
            echo "COMPILATION_FLAG3=false" >> $GITHUB_ENV            
          fi

          echo "${{ env.COMPILATION_FLAG2 }}"
          echo "${{ env.COMPILATION_FLAG3 }}"
          
      - name: Build Project
        if: ${{ env.COMPILATION_FLAG == 'true' }}
        run: |
          echo "${{ env.COMPILATION_FLAG2 }}"
          echo "cd ${{ matrix.project.path }}"
          echo "mkdir build"
          echo "cd build"
          echo "cmake .."
          echo "make"
