on: push
name: CI
jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: # Filter , compilation path
          - ['src.*one.*cpp', /src/one]
          - ['src.*two.*cpp', /src/two]
    steps:
      # Prepare project repository.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # We need to fetch 2 commits to get the diff.
      
      - name: Get differences
        run: |
          DIFFS="$(git diff --name-only HEAD HEAD~1)"
          CHANGES="$(echo $DIFFS | grep '${{ matrix.project[0] }}')"
          echo "FLAG=$?" >> $GITHUB_ENV
          
      - name: Differences on current module
        if: env.FLAG == 0
        run: |
          echo "cd ${{ matrix.project[1] }}"
          echo "mkdir build"
          echo "cd build"
          echo "cmake .."
          echo "make"