on: push
name: CI
jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - dependencies: 'src.*one.*cpp|src.*two.*cpp'
            path: src/one
          - dependencies: 'src.*two.*cpp'
            path: src/two
    steps:
      # Prepare project repository.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # We need to fetch 2 commits to get the diff.
      
      - name: Check for compilation requirement
        id: test
        run: |
          
          DIFFS=$(git diff --name-only HEAD HEAD~1)
          if echo $DIFFS | grep -E '${{ matrix.project.dependencies }}'; then
            echo "COMPILATION_FLAG=true" >> $GITHUB_ENV
            echo "COMPILATION_FLAG2=\"true\"" >> $GITHUB_ENV
          else
            echo "COMPILATION_FLAG=false" >> $GITHUB_ENV
            echo "COMPILATION_FLAG3=true" >> $GITHUB_ENV            
            echo "COMPILATION_FLAG3=false" >> $GITHUB_ENV            
          fi

          echo "::set-output name=flag1::value1"
          echo "::set-output name=flag2::value2"
          echo "::set-output name=flag3::value3"
          echo "::set-output name=flag1::value3"
          
      - name: Build Project
        if: ${{ env.COMPILATION_FLAG == 'true' }}
        run: |
          echo "Flag 1: ${{ steps.step1.outputs.flag1 }}"
          echo "Flag 2: ${{ steps.step1.outputs.flag2 }}"
          echo "Flag 3: ${{ steps.step1.outputs.flag3 }}"
          echo "Flag 4: ${{ steps.step1.outputs.flag4 }}"
