on: push
name: CI
jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - dependencies: 'src.*one.*cpp|src.*two.*cpp'
            path: src/one
          - dependencies: 'src.*two.*cpp'
            path: src/two
    steps:
      # Prepare project repository.
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Check for compilation requirement
        id: test
        run: |
          DIFFS=$(git diff --name-only HEAD origin/${{ github.head_ref }})
          echo $DIFFS
