on: push
name: CI
jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dependencies:
          - 'src.*one.*cpp|src.*two.*cpp'
          - 'src.*two.*cpp'
        path:
          - src/one
          - src/two
    steps:
      # Prepare project repository.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # We need to fetch 2 commits to get the diff.
      
      - name: Check for compilation requirement
        run: |
          
          DIFFS=$(git diff --name-only HEAD HEAD~1)
          GREP=$(grep -E ${{ matrix.dependencies }})
          if echo $DIFFS | $GREP"; then
            echo "COMPILATION_FLAG=true" >> $GITHUB_ENV
          else
            echo "COMPILATION_FLAG=false" >> $GITHUB_ENV
          fi
          
      - name: Build Project
        if: ${{ env.COMPILATION_FLAG == 'true' }}
        run: |
          echo "cd ${{ matrix.project[1] }}"
          echo "mkdir build"
          echo "cd build"
          echo "cmake .."
          echo "make"