on: push
name: CI
jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest
    steps:
      # Prepare project repository.
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get differences
        id: all_diffs
        run: |
          git fetch --all
          git diff HEAD^ HEAD

      - name: Filter differences
        run: cat $ {{ steps.all_diffs }} | grep src | grep cpp
        id: filtered_diffs
        
      - name: Check for differences
        if: env.GIT_DIFF
        run: |
          echo ${{ steps.filtered_diffs }}
