name: System tests
run-name: System tests

on:
  schedule:
    # Run every day at UTC midnight.
    - cron: '*/5 * * * *'

env:
  PYTHON: python3.10
  RTR_SCRIPT: .rtr/rtr.py
  OUTPUT_DIR: /tmp
  CICD_STEPS_DESC_FILE: .rtr/rtr_cicd.json
  INSTALL_STEPS_DESC_FILE: .rtr/rtr_install.json
  CACHE_KEY_BASENAME: main-ccache

  # Reduce the timeout for downloading cache segments to 1 minute.
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1

jobs:

  # Check if there has been any commit in the last 24 hours.
  check-last-commits:
    runs-on: ubuntu-22.04
    outputs:
      should_execute: ${{ steps.check_commit.outputs.should_execute }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Check last commits
        id: check_commit
        run: >
          LAST_COMMITS=$(git rev-list --after="15 minutes" ${{ github.sha }}) &&
          echo $LAST_COMMITS &&
          if test -z "$LAST_COMMITS"; then
                echo "should_execute=false" >> $GITHUB_OUTPUT
          else
                echo "should_execute=true" >> $GITHUB_OUTPUT
          fi

  run-system-tests:
    needs: check-last-commits
    if: needs.check-last-commits.outputs.should_execute == 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: Only if recent commits
        run: echo "This step should run only if there are recent commits"
